decoder:
  decoder_lat_dim: 512
  decoder_hidden_dim: 1024
  decoder_nlayers: 8
  decoder_out_dim: 1
  use_mapping: True



training:
  root_dir: dataset/leaf_classification/images
  root_dir_color: dataset/LeafData
  save_path: checkpoints/2dShape
  save_name: exp-sdf2d
  batch_size: 1
  ckpt_interval: 50
  ckpt_vis: 5
  grad_clip: 0.1
  grad_clip_lat: 0.1
  lr: 0.0001
  lr_lat: 0.0001
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.5
  lr_decay_interval: 30
  lr_decay_interval_lat: 30

  npoints_decoder: 2000
  npoints_decoder_non: 1000

  sigma_near: 0.001
  weight_decay: 0.02
  lambdas: 
    lat_reg: 0.002
    surf_sdf: 1
    normals: 0.3
    space_sdf: 1
    near_udf: 1
    grad: 0.1
    anchors: 0.0
    symm_dist: 0.0
    middle_dist: 0.0