decoder:
  decoder_lat_dim: 512
  decoder_hidden_dim: 1024
  decoder_nlayers: 8
  decoder_out_dim: 1

training:
  root_dir: dataset/ScanData
  root_dir_color: dataset/LeafData
  save_path: checkpoints/cg_bs8
  batch_size: 8

  ckpt_interval: 500
  grad_clip: 0.1
  grad_clip_lat: 0.1
  lr: 0.0005
  lr_lat: 0.001
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.5
  lr_decay_interval: 500
  lr_decay_interval_lat: 500
  npoints_decoder: 2000
  npoints_decoder_non: 500
  sigma_near: 0.0001
  weight_decay: 0.02
  lambdas: 
    lat_idx: 0.002
    lat_spc: 0.002
    surf_udf: 2
    normals: 0.2
    space_far: 1
    space_near: 1
    grad: 0.1
    anchors: 0.0
    symm_dist: 0.0
    middle_dist: 0.0
