decoder:
  decoder_lat_dim: 512
  decoder_hidden_dim: 1024
  decoder_nlayers: 8
  decoder_out_dim: 1
  use_mapping: False



training:
  root_dir: dataset/leaf_classification/images
  root_dir_color: dataset/LeafData
  save_path: checkpoints/3dShape
  save_name: exp-3dShape
  batch_size: 1
  ckpt_interval: 500
  ckpt_vis: 50
  grad_clip:   #0.1
  grad_clip_lat: 0.1
  lr: 0.0005
  lr_lat: 0.001
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.5
  lr_decay_interval: 2000
  lr_decay_interval_lat: 2000

  npoints_decoder: 2000
  npoints_decoder_space: 500

  sigma_near: 0.01
  weight_decay: 0.02
  lambdas: 
    lat_reg: 0.01
    surf_sdf: 2
    normals: 0.3
    space_sdf: 0.1
    grad: 0.1
