shape_decoder:
  decoder_lat_dim: 512
  decoder_hidden_dim: 1024
deform_decoder:
  decoder_hidden_dim: 512
  decoder_lat_dim: 200
  decoder_nblocks: -1
encoder: null
has_forward: true
training:
  save_path: checkpoints/
  root_dir: dataset/ScanData
  root_dir_color: dataset/LeafData
  batch_size: 64
  ckpt_interval: 5000
  grad_clip: 0.025
  grad_clip_lat: 0.025
  npoints_decoder: 2000
  npoints_decoder_non: 250
  sigma_near: 0.001
  weight_decay: 0.02
  lambdas:
    lat_reg: 5.0e-05
    w_distance: 1
    # loss_D_fake: 1
    loss_G: 1
    loss_mse: 1
    gradient_penalty: 1
    loss_per: 0.2
  lambda_pen:  10
  lr: 0.00001
  lr_decay_factor: 0.2
  lr_decay_factor_lat: 0.2
  lr_decay_interval: 1000
  lr_decay_interval_lat: 1000
  lr_lat: 0.005
  npoints_decoder: 1000
  shape_ckpt: 30000
  shape_exp_name: SHAPE_EXP_NAME
  sigma_near: 0.01
  weight_decay: 1.0e-05
