decoder:
  decoder_lat_dim: 128
  decoder_hidden_dim: 1024
  decoder_nlayers: 8
  decoder_out_dim: 1
  use_mapping: False



training:
  root_dir: dataset/leaf_classification/canonical_mesh
  save_path: checkpoints/shape
  save_name: Shape_new
  batch_size: 8
  ckpt_interval: 1000
  ckpt_vis: 500
  grad_clip:   #0.1
  grad_clip_lat: 0.1
  lr: 0.0005
  lr_lat: 0.001
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.5
  lr_decay_interval: 1000
  lr_decay_interval_lat: 1000

  npoints_decoder: 2000
  npoints_decoder_space: 1000

  sigma_near: 0.01
  weight_decay: 0.02
  lambdas: 
    lat_reg: 0.01
    surf_sdf: 2
    normals: 0.3
    space_sdf: 0.01
    grad: 0.1
