shape_decoder:
  decoder_lat_dim: 128
  decoder_hidden_dim: 1024
  decoder_out_dim: 1
  decoder_nlayers: 8
  use_mapping: False

deform_decoder:
  decoder_hidden_dim: 1024
  decoder_lat_dim: 128
  decoder_nlayers: 8
  decoder_out_dim: 3
  use_mapping: False

training:
  shape_checkpoints: checkpoints/2dShape/exp-sdf2d__1000.tar
  root_dir: dataset/ScanData/deformation
  save_name: exp-inference
  save_path: checkpoints/inference
  train_color: 1000
  use_nce: False
  use_distance: True
  batch_size: 64
  ckpt_interval: 100
  ckpt_vis: 1000
  grad_clip: 0.025
  grad_clip_lat: 0.025
  npoints_decoder: 2000
  weight_decay: 0.02
  lambdas:
    loss_latent_shape: 1
    loss_latent_deform: 1
    loss_camera_pose: 1
    loss_texture: 1
  lr: 0.0001
  lr_cam: 0.001
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.2
  lr_decay_interval: 10
  lr_decay_interval_lat: 10
  lr_lat: 0.005
  npoints_decoder: 1000
  shape_ckpt: 30000
  sigma_near: 0.01
  weight_decay: 1.0e-05
